<%@ Page Language="C#" AutoEventWireup="true" CodeFile="howto.aspx.cs" Inherits="_Default" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
     <style type="text/css">
        h1
        {
            color:black:
        }
        h3
        {
            color:B;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div style="height: 576px; background-color: #66FF99; background-image: url('Pic/howtoplay2.jpg'); width: 1444px;">
    <center><h1>HOW TO PLAY??</h1></center>
        <ul>
            <li><h3>DYNAMIC SUDOKU is another type of SUDOKU like game where the logic is bit diffrent.</h3></li>
            <li><h3>In DYNAMIC SUDOKU the Matrix Constaint is 3x3 to 7x7.You can chose any number between 3 to 7.</h3></li>
            <li><h3>You have to match the Row and Coloum Condition which is generated by the game.Means if you chose 3x3 Matrix then your aim(value) is to make 15 in each Row And Coloum.Depending on nxn Matrix your aim(value) will be generated.</h3></li>
            <li><h3>In case of Sudoku your elements are(1,2,3,4,.....)depending on the Size of Matrix.But In case of Dynamic Sudoku the values are diffrent means if ypu chose 3x3 matrix yhen the values are Dynamically Generated like(4,5,6) and in every new game the value will be generated.Nothing is Constaint in Dynamic Sudoku.</h3></li>
            <li><h3>The values are not repeted in Case of Dynamic Sudoku means if you chose 5x5 Matrix the values may(10,12,5,18,20)but it can never be(<u>10</u>,12,15,<u>10</u>,18).</h3></li>
            <li><h3>You have to find the values by Observing the game.</h3>
            </li>
        </ul>
        <h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:Button ID="Button4" runat="server" OnClick="Button4_Click" Text="BACK" Width="85px" BorderColor="#003366" BorderStyle="Dashed" />
            &nbsp;</h4>
    </div>
    </form>
</body>
</html>
